services:
  app:
    build:
      context: .
      dockerfile: ./container-app-build/Dockerfile
    restart: unless-stopped
    volumes:
      - ./container-app:/app:ro
    environment:
      GOOGLE_RECAPTCHA_SITE_KEY: "${GOOGLE_RECAPTCHA_SITE_KEY:-null}"
      GOOGLE_RECAPTCHA_SECRET_KEY: "${GOOGLE_RECAPTCHA_SECRET_KEY:-null}"
      IPINFO_TOKEN: "${IPINFO_TOKEN:-null}"
      DISCORD_WEBHOOK_URL: "${DISCORD_WEBHOOK_URL:-null}"
