-- FUNCTION
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';
-- TABLE
DROP VIEW IF EXISTS users_view;
DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
-- TRIGGER
CREATE OR REPLACE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
-- VIEW
CREATE OR REPLACE VIEW users_view AS
    SELECT
        u.id,
        u.created_at,
        u.updated_at
    FROM
        users u
-- DROP VIEW IF EXISTS USERS_CURRENT_RESIN_LOG_VIEW;
-- CREATE OR REPLACE VIEW USERS_CURRENT_RESIN_LOG_VIEW AS
-- SELECT
--     TO_CHAR(
--         UPDATED_AT AT TIME ZONE 'Asia/Tokyo',
--         'FMMM/FMDD HH24:MI:SS'
--     ) AS UPDATED_AT,
--     ENKA_PLAYERINFO_NICKNAME AS PLAYER_NICKNAME,
--     ENKA_PLAYERINFO_SIGNATURE AS PLAYER_SIGNATURE,
--     ENKA_UID,
--     ENKA_REGION,
--     ENKA_TTL,
--     HOYOLAB_CURRENT_RESIN AS CURRENT_RESIN,
--     HOYOLAB_MAX_RESIN AS MAX_RESIN,
--     HOYOLAB_RESIN_RECOVERY_TIME AS RESIN_RECOVERY_TIME
-- FROM
--     PUBLIC.USERS U
-- WHERE
--     ENKA_PLAYERINFO_NICKNAME IS NOT NULL
-- ORDER BY
--     ID ASC;
